apiVersion: v2
name: alquimia-slight
description: Helm chart for Alquimia Slight, part of Alquimia Vision
type: application
version: 0.1.1
appVersion: "0.1.1"

keywords:
  - alquimia
  - vision
  - appliance
  - edge
  - vlm

home: https://alquimia.ai

maintainers:
  - name: Alquimia

dependencies:
  - name: nats
    version: "1.2.8"
    repository: "https://nats-io.github.io/k8s/helm/charts/"
    condition: nats.enabled