global:
  host: "192.168.77.143"

product:
  os: "RHEL 10 AI"
  targetPlatform: "appliance"

bff:
  secret:
    jwtSecret: "change-me"
    bootstrapAdminUsername: "adminBff"
    bootstrapAdminPassword: "change-me"

postgres:
  auth:
    username: bffUser
    password: change-me
  persistence:
    enabled: true
    size: 10Gi
    storageClass: longhorn

minio:
  persistence:
    enabled: true
    size: 20Gi
    storageClass: longhorn