{{- if .Values.bff.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alquimia-slight.bff.fullname" . }}-secret
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
    app.kubernetes.io/component: bff
type: Opaque
stringData:
  ARGOS_BFF_DB_URL: "postgresql+asyncpg://{{ .Values.postgres.auth.username }}:{{ .Values.postgres.auth.password }}@{{ include "alquimia-slight.postgres.fullname" . }}:{{ .Values.postgres.service.port }}/{{ .Values.postgres.auth.database }}"
  ARGOS_BFF_STORAGE_ACCESS_KEY: "{{ .Values.minio.rootUser }}"
  ARGOS_BFF_STORAGE_SECRET_KEY: "{{ .Values.minio.rootPassword }}"
  ARGOS_BFF_JWT_SECRET: "{{ .Values.bff.secret.jwtSecret }}"
  ARGOS_BFF_BOOTSTRAP_ADMIN_USERNAME: "{{ .Values.bff.secret.bootstrapAdminUsername }}"
  ARGOS_BFF_BOOTSTRAP_ADMIN_PASSWORD: "{{ .Values.bff.secret.bootstrapAdminPassword }}"
  ARGOS_BFF_MEDIA_GATEWAY_INTERNAL_READER_TOKEN: "{{ .Values.bff.secret.mediamtxInternalReaderToken }}"
  ARGOS_VIRTUAL_CAMERA_STORAGE_ACCESS_KEY: "{{ .Values.minio.rootUser }}"
  ARGOS_VIRTUAL_CAMERA_STORAGE_SECRET_KEY: "{{ .Values.minio.rootPassword }}"
  ARGOS_VIRTUAL_CAMERA_PUBLISH_TOKEN: "{{ default .Values.bff.secret.mediamtxInternalReaderToken .Values.bff.secret.virtualCameraPublishToken }}"
{{- end }}
