{{- if .Values.vlm.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alquimia-slight.vlm.fullname" . }}-secret
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
    app.kubernetes.io/component: vlm
type: Opaque
stringData:
  VLLM_API_KEY: {{ .Values.vlm.model.apiKey | quote }}
{{- end }}