{{- if .Values.web.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alquimia-slight.web.fullname" . }}-config
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  VITE_APP_TIME_ZONE: {{ .Values.web.config.viteAppTimeZone | quote }}
  VITE_BFF_URL: {{ .Values.web.config.viteBffUrl | quote }}
  MEDIAMTX_PUBLIC_HOST: {{ .Values.web.config.mediamtxPublicHost | quote }}
  MEDIAMTX_WEBRTC_ALLOW_ORIGINS: {{ .Values.web.config.mediamtxWebrtcAllowOrigins | quote }}
  MEDIAMTX_WEBRTC_ADDITIONAL_HOSTS: {{ .Values.web.config.mediamtxWebrtcAdditionalHosts | quote }}
{{- end }}
