{{- if .Values.otel.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alquimia-slight.fullname" . }}-otel
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel
type: Opaque
stringData:
  ARGOS_OTEL_LOGS_ENABLED: {{ .Values.otel.logsEnabled | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.otel.exporterOtlpProtocol | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ .Values.otel.exporterOtlpEndpoint | quote }}
  OTEL_RESOURCE_ATTRIBUTES: {{ .Values.otel.resourceAttributes | quote }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ .Values.otel.exporterOtlpHeaders | quote }}
{{- end }}
