{{- if include "alquimia-slight.observability.apps.enabled" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "alquimia-slight.otel.secretName" . }}
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
    app.kubernetes.io/component: otel
type: Opaque
stringData:
  ARGOS_OTEL_LOGS_ENABLED: {{ .Values.observability.apps.logsEnabled | quote }}
  OTEL_EXPORTER_OTLP_PROTOCOL: {{ .Values.observability.apps.exporterOtlpProtocol | quote }}
  OTEL_EXPORTER_OTLP_ENDPOINT: {{ include "alquimia-slight.otel.effectiveEndpoint" . | quote }}
  OTEL_RESOURCE_ATTRIBUTES: {{ .Values.observability.apps.resourceAttributes | quote }}
  OTEL_EXPORTER_OTLP_HEADERS: {{ .Values.observability.apps.exporterOtlpHeaders | quote }}
{{- end }}
