{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "alquimia-slight.serviceAccountName" . }}
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
imagePullSecrets:
{{- range .Values.global.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}