{{- if .Values.web.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "alquimia-slight.web.fullname" . }}-config
  labels:
    {{- include "alquimia-slight.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  VITE_APP_TIME_ZONE: {{ .Values.web.config.viteAppTimeZone | quote }}
  VITE_BFF_URL: {{ include "alquimia-slight.web.viteBffUrl" . | quote }}
  MEDIAMTX_PUBLIC_HOST: {{ include "alquimia-slight.web.mediamtxPublicHost" . | quote }}
  MEDIAMTX_WEBRTC_ALLOW_ORIGINS: {{ include "alquimia-slight.web.mediamtxWebrtcAllowOrigins" . | quote }}
  MEDIAMTX_WEBRTC_ADDITIONAL_HOSTS: {{ include "alquimia-slight.web.mediamtxWebrtcAdditionalHosts" . | quote }}
{{- end }}
